graded-assignments/course02/module04/todolists/config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  root to: "todo_lists#index"

  resources :sessions, only: [:new, :create, :destroy] 

=======
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02
  resources :todo_lists

  resources :todo_lists do
    resources :todo_items
  end

<<<<<<< HEAD
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
=======
  root to: "todo_lists#index"
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02

end

graded-assignments/course02/module04/todolists/app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	belongs_to :user
	has_many :todo_items, dependent: :destroy

	default_scope { order :list_due_date }
end

graded-assignments/course02/module04/todolists/app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
<<<<<<< HEAD
    @todo_lists = current_user.todo_lists.paginate(page: params[:page], per_page: 8)
=======
    @todo_lists = TodoList.all
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
<<<<<<< HEAD
    @todo_list = current_user.todo_lists.new
=======
    @todo_list = TodoList.new
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
<<<<<<< HEAD
    @todo_list = current_user.todo_lists.new(todo_list_params)
=======
    @todo_list = TodoList.new(todo_list_params)
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
<<<<<<< HEAD
      @todo_list = current_user.todo_lists.find(params[:id])
=======
      @todo_list = TodoList.find(params[:id])
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:list_name, :list_due_date)
    end
end

graded-assignments/course02/module04/todolists/app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

graded-assignments/course02/module04/todolists/app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_name %><br>
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :list_due_date %><br>
    <%= f.date_select :list_due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

graded-assignments/course02/module04/todolists/app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

graded-assignments/course02/module04/todolists/app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>List name</th>
      <th>List due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.list_name %></td>
        <td><%= todo_list.list_due_date %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
<<<<<<< HEAD
        <td><%= link_to 'Destroy', todo_list, method: :delete %></td>
=======
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02
      </tr>
    <% end %>
  </tbody>
</table>
<<<<<<< HEAD
<p/>

<%= will_paginate @todo_lists %>
=======
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

graded-assignments/course02/module04/todolists/app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

graded-assignments/course02/module04/todolists/app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List name:</strong>
  <%= @todo_list.list_name %>
</p>

<p>
  <strong>List due date:</strong>
  <%= @todo_list.list_due_date %>
</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list.todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.title %></td>
        <td><%= todo_item.due_date %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.completed %></td>
        <td><%= link_to 'Show', [@todo_list, todo_item] %></td>
<<<<<<< HEAD
        <td><%= link_to 'Destroy', [@todo_list, todo_item], method: :delete %></td>
=======
        <td><%= link_to 'Destroy', [@todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
>>>>>>> 2c439b8be001a1e2440496d55bde3b2670224c02
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Todo Item', new_todo_list_todo_item_path(@todo_list) %>
<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>